Leonni/Controllers/CPFrontController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using Leonni.Core.Controllers;
using Leonni.Models.ViewModels;
using Leonni.Models.ModelMappers;
using System.IO;
using Leonni.Core;
using MoreLinq;
using Leonni.Models;
using Leonni.Models.Binder;

namespace Leonni.Controllers
{
    public partial class ControlPanelController : LeonniApplicationController
    {
        //
        // GET: /CPFront/

        public ActionResult Front()
        {
            ViewBag.CurrentMainTab = "Front";
            ViewBag.CurrentSubTab = "Profile";
            ViewBag.CurrentSuperSubTab = "Name";
            VideoLinkModel objVideoLink = new VideoLinkModel();
            FrontModel objFront = new FrontModel();
            objFront.VideoLinkModel = objVideoLink;

            List<SectionModel> objSection = new List<SectionModel>();
            objSection = SectionMap.Map(_repoSection.GetList(x => x.LanguageId == 1).ToList());
            objFront.SectionListModel = objSection;
            return View("Front", objFront);
        }

        [HttpPost]
        public ActionResult Front(FrontModel objFrontModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (!string.IsNullOrEmpty(objFrontModel.VideoLinkModel.VideoLinkUrl))
                    {
                        objFrontModel.VideoLinkModel.CreatedDate = DateTime.Now;
                        objFrontModel.VideoLinkModel.SectionId = 0;
                        var vidLink = VideoLinkMap.Map(objFrontModel.VideoLinkModel);
                        _repoVideoLink.Add(vidLink);
                        _repoVideoLink.Save();
                    }
                    if (objFrontModel.BannerPic != null && objFrontModel.BannerPic.InputStream != null)
                    {
                        var file = new Models.File();

                        file.ContentType = objFrontModel.BannerPic.ContentType;
                        file.FileName = objFrontModel.BannerPic.FileName;

                        var memoryStream = new MemoryStream();
                        objFrontModel.BannerPic.InputStream.CopyTo(memoryStream);

                        file.Content = memoryStream.ToArray();
                        file.Link = objFrontModel.FileLink;

                        _repoFile.Add(file);
                        _repoFile.Save();

                        FrontEntityFileModel efModel = new FrontEntityFileModel();
                        var entityFile = FrontEntityFileMap.Map(efModel);
                        entityFile.SectionId = 0;
                        entityFile.EntityId = 0;
                        entityFile.FileId = file.Id;
                        _repoFrontEntityFile.Add(entityFile);
                        _repoFrontEntityFile.Save();
                    }
                }
                return View(objFrontModel);
            }
            catch (Exception e)
            {
                return View(objFrontModel);
            }
        }

        [HttpPost]
        public ActionResult FrontSection(FrontModel objFrontModel, FormCollection fc)
        {
            try
            {
                long sectionId = long.Parse(fc["sectionId"]);
                if (ModelState.IsValid)
                {
                    if (!string.IsNullOrEmpty(objFrontModel.VideoLinkModel.VideoLinkUrl))
                    {
                        objFrontModel.VideoLinkModel.CreatedDate = DateTime.Now;
                        objFrontModel.VideoLinkModel.SectionId = sectionId;
                        var vidLink = VideoLinkMap.Map(objFrontModel.VideoLinkModel);
                        _repoVideoLink.Add(vidLink);
                        _repoVideoLink.Save();
                    }
                    if (objFrontModel.BannerPic != null && objFrontModel.BannerPic.InputStream != null)
                    {
                        var file = new Models.File();

                        file.ContentType = objFrontModel.BannerPic.ContentType;
                        file.FileName = objFrontModel.BannerPic.FileName;

                        var memoryStream = new MemoryStream();
                        objFrontModel.BannerPic.InputStream.CopyTo(memoryStream);

                        file.Content = memoryStream.ToArray();
                        file.Link = objFrontModel.FileLink;

                        _repoFile.Add(file);
                        _repoFile.Save();

                        FrontEntityFileModel efModel = new FrontEntityFileModel();
                        var entityFile = FrontEntityFileMap.Map(efModel);
                        entityFile.SectionId = sectionId;
                        entityFile.EntityId = 0;
                        entityFile.FileId = file.Id;
                        _repoFrontEntityFile.Add(entityFile);
                        _repoFrontEntityFile.Save();
                    }
                }
                return View("Front", objFrontModel);
            }
            catch (Exception e)
            {
                return View("Front", objFrontModel);
            }
        }


        public PartialViewResult FrontSearch()
        {
            //long sectionId = 0;
            //if (HttpContext.Items["one"] != null)
            //{
            long sectionId = long.Parse(HttpContext.Items["one"].ToString());
            //}
            FrontModel objFront = new FrontModel();
            List<VideoLinkModel> lstVideo = new List<VideoLinkModel>();

            lstVideo = VideoLinkMap.Map(_repoVideoLink.GetList(x => x.SectionId == sectionId).OrderBy(x => x.CreatedDate).ToList());

            FrontModel fModel = new FrontModel();
            fModel.VideoListModel = lstVideo;

            List<FrontEntityFileModel> lstFrontEntityFile = new List<FrontEntityFileModel>();
            lstFrontEntityFile = FrontEntityFileMap.Map(_repoFrontEntityFile.GetList(x => x.SectionId == sectionId).OrderBy(x => x.Id).ToList());
            fModel.FrontEntityFileListModel = lstFrontEntityFile;
            return PartialView("_FrontList", fModel);
            //return View(fModel);
        }

        //public PartialViewResult FrontList()
        //{
        //    List<VideoLinkModel> lstVideo = new List<VideoLinkModel>();   

        //    lstVideo = VideoLinkMap.Map(_repoVideoLink.GetList().OrderBy(x => x.CreatedDate).ToList());
        //    FrontModel fModel = new FrontModel();
        //    fModel.VideoListModel = lstVideo;
        //    return PartialView("_FrontList", fModel);
        //}

    }
}

Leonni/Controllers/FileController.cs
using System.Drawing.Imaging;
using System.IO;
using System.Web.Mvc;
using Leonni.Core;
using Leonni.Interfaces;
using Leonni.Core.Controllers;

namespace Leonni.Controllers
{
    public class FileController : LeonniApplicationController
    {
        IFileRepository _repoFile;

        public FileController(IFileRepository repoFile)
        {
            _repoFile = repoFile;
        }

        public FileContentResult Picture(long id, int width, int height)
        {
            var file = _repoFile.GetSingle(x => x.Id == id);
            if (file != null)
            {
                MemoryStream output = new MemoryStream();

                if (file != null && file.Content.Length > 0 && file.ContentType.StartsWith("image/"))
                {
                    ImageResizer resizer = null;
                    if (file.Height < file.Width || file.Height == null || file.Width==null)
                    {
                         resizer = new ImageResizer(width, height, false, ImageFormat.Jpeg);
                    }
                    else
                    {
                         resizer = new ImageResizer(width, height, true, ImageFormat.Jpeg);
                    }


                    Stream stream = new MemoryStream(file.Content);
                    resizer.Resize(stream, out output);
                }
                else if (file != null && !file.ContentType.StartsWith("image/"))
                {
                    return null;
                }
                return new FileContentResult(output.ToArray(), file.ContentType);
            }
            else
                return null;

        }

    }
}

Leonni/Views/Group/Add.cshtml
@model Leonni.Models.ViewModels.GroupModel
@{
    ViewBag.Title = "Add Group";
}
<h2>
    Edit Group</h2>
@using (Html.BeginForm("add", "Group", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)

    @*@Html.Hidden("CreatedBy", Membership.GetUser().ProviderUserKey)*@
    <fieldset>
        <legend>Group</legend>
        
      
        <div class="editor-label">
            @Html.LabelFor(model => model.DisciplineId)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.DisciplineId, (IEnumerable<SelectListItem>)ViewBag.DisciplineId, "Choose discipline")
            @Html.ValidationMessageFor(model => model.DisciplineId)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Summary)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Summary)
            @Html.ValidationMessageFor(model => model.Summary)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Text)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Text)
            @Html.ValidationMessageFor(model => model.Text)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.IsVisible)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IsVisible)
            @Html.ValidationMessageFor(model => model.IsVisible)
        </div>

         <div class="editor-label">
            @Html.LabelFor(model => model.IsCloseIncome)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IsCloseIncome)
            @Html.ValidationMessageFor(model => model.IsCloseIncome)
        </div>

         <div class="editor-label">
            @Html.LabelFor(model => model.AllowContents)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AllowContents)
            @Html.ValidationMessageFor(model => model.AllowContents)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CountryId)
        </div>
        <div class="editor-field">
            <select name="CountryId" id="CountryId">
            </select>
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.StateId)
        </div>
        <div class="editor-field">
            <select name="StateId" id="StateId">
            </select>
        </div>
       
        <div class="editor-label">
            @Html.LabelFor(model => model.GroupPic)
            @Html.ValidationMessageFor(model => model.GroupPic)
        </div>
        <div class="editor-field">
            <input type="file" name="GroupPic" />
        </div>
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}
@section scripts {
    <script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
    @*@Scripts.Render("~/bundles/jqueryval")*@
    <script type="text/javascript">
        $(function () {
            var data = [];
            GetCountries();

            function GetCountries() {
                $.getJSON('@Url.Action("GetCountryList", "Group")', {}, function (response) {
                    if (response && response.count > 0) {
                        data = [];
                        $('#CountryId').html('<option value=""></option>');

                        $.each(response.countries, function (index, item) {
                            var option = "<option value=" + item.ID + " >" + item.Name + "</option>";
                            $('#CountryId').append(option);

                            data[item.ID] = item;
                        });

                    }
                });

                $('#CountryId').change(function () {
                    var id = $(this).val();

                    var country = data[id];

                    $('#StateId').html('<option value=""></option>');
                    $.each(country.States, function (index, item) {
                        var option = "<option value=" + item.ID + " >" + item.Name + "</option>";
                        $('#StateId').append(option);
                    });
                });
            }

            $('form').submit(function (e) {
                //e.preventDefault();
            });
        });
    </script>
}

Leonni/Views/Group/Index.cshtml
@model GroupModel
@{
    ViewBag.Title = "Index";
}
<div id="content-wrapper">
    <div class="middle-hr">
    </div>
    <div id="banner">
        <img src="@Url.Action("Picture", "File", new { id = Model.AdvertisingBanner, width = 720, height = 234 })" alt="" />
    </div>
    <div id="youtube-container">
        <iframe width="720" height="450" src="@Model.VideoUrl" frameborder="0" allowfullscreen>
        </iframe>
    </div>
    <div id="image-showcase">
        @if (Model.BannerList != null)
        {
            foreach (var objModel in Model.BannerList)
            { 
            <img src="@Url.Action("Picture", "File", new { id = objModel.FileId, width = 720, height = 234 })" alt="" /><br />
            }
        }
    </div>
    
    <div id="contents">
    @{Html.RenderAction("GroupSearch", "Group");}
    </div>
    
    @section RightMenu
{
        @{Html.RenderPartial("NormalRightMenu");}
    }
    <script src="~/Scripts/GlobalSearch.js" type="text/javascript"></script>
    
    <script type="text/javascript">
        if ($("#user-list-partial").length > 0) {
            List(currentPageNumber, takeNumber, "visitorsGroup");
        }
    </script>

Leonni/Views/Group/ViewGroup.cshtml
@model GroupModel
@{
    ViewBag.Title = "ViewGroup";
    var commentUrl = ViewData["Url"] ?? "";
    var userID = "f22511dc-37d7-456d-9da7-2b9dbbe316e0";
    var profileId = ViewData["ProfileId"];
    var entityId = ViewData["EntityId"];
    var sectionId = ViewData["SectionId"];
}
<div id="content-wrapper">
    <div class="user-page">
        <div class="middle-hr">
        </div>
        <div class="clear">
        </div>
        <div class="search-result">
            <div class="search-image">
                <img src="@Url.Action("Picture", "File", new { id = @ViewBag.FileId, width = 150, height = 120 })" alt="" /></div>
            <div class="search-content">
                <a href="#" class="name">@ViewBag.DisciplineName </a><span>|</span><a href="#" class="sub-name">@Html.DisplayFor(modelItem => modelItem.CountryName)</a><span>|</span><a
                    href="#" class="categories">@ViewBag.ProvinceName</a><span>|</span><a href="#" class="categories">@Html.DisplayFor(modelItem => modelItem.Summary)</a></div>
            <div class="clear">
            </div>
        </div>
        <div class="user-biodata">
            <div style="margin: 5px 0">
                Content</div>
            <div class="middle-hr">
            </div>
        </div>
        <div class="blue-btn view-profile-btn" style="margin-bottom: 15px;">
            <input type="button" id="toggle" value="Read Comments" /></div>
        <div class="middle-hr comments" style="display: none">
            @Html.Partial("Comments", new ViewDataDictionary { { "Url", Request.RawUrl.ToString() }, { "ProfileId", profileId }, { "SectionId", sectionId }, { "EntityID", entityId } })
        </div>
        <div id="contents">
            @{Html.RenderAction("GroupContents", "Group", new { id = Model.Id });}
        </div>
    </div>
</div>
@section RightMenu
{
    @if (Request.IsAuthenticated)
    { 
        <p>
            <ul>
                <li><a href="javascript:void(0);">@User.Identity.Name</a> </li>
                <li>
                    @Html.ActionLink("Log Out", "LogOff", "Account")
                </li>
            </ul>
        </p>
    }
    <div style="background: none repeat scroll 0 0 #EFEFEF">
        <div>
            <ul>
                <li>Statistics</li>
                <li>by @Model.CreatedBy </li>
                @if (@Model.isFavourite)
                { 
                    <li><a href="javascript:void(0);" onclick="AddtoFavourites(@Model.Id,2)" id="favourites">
                        Remove to Favourites</a></li>
                }
                else
                {
                    <li><a href="javascript:void(0);" onclick="AddtoFavourites(@Model.Id,2)" id="favourites">
                        Add to Favourites</a></li>
                }
                <li>123 Files Published</li>
                <li>From @Model.CreatedDate</li>
            </ul>
        </div>
    </div>
    <div class="right-hr">
    </div>
    <div>
        <input type="checkbox" />
        Notify me if published
    </div>
    <div class="right-hr">
    </div>
    @using (Ajax.BeginForm("SendMessage", "ControlPanel", new { id = @Model.Id }, new AjaxOptions { OnBegin = "OnBegin", OnSuccess = "OnSuccess" }))
    {
        <div class="right-comment">
            <div class="text-area">
                @Html.TextArea("Message")
            </div>
            <div class="blue-btn" style="margin: 5px 0; float: right;">
                <input name="" type="submit" value="Send" /></div>
            <div class="clear">
            </div>
        </div>
    }
    <div class="right-hr">
    </div>
}
<script src="~/Scripts/GlobalSearch.js" type="text/javascript"></script>
<script type="text/javascript">
    if ($("#user-list-partial").length > 0) {
        List(currentPageNumber, takeNumber, "viewGroupContents");
    }


    function AddtoFavourites(entityId, sectionId) {
        $.ajax({
            url: LeonniUrl("/Group/AddRemovetoFavourites"),
            type: "POST",
            data: { id: entityId, sectionId: sectionId },
            dataType: "json",
            success: function (response) {
                if (response.status == "success") {
                    if (response.message == "added") {
                        $("#favourites").html("Remove From Favourites");
                    }
                    else {
                        $("#favourites").html("Add From Favourites");
                    }
                }
                else if (response.status == "error") {
                    Leonni.ShowErrorMessage(response.errors);
                }
            }

        });
    }

    $(document).ready(function () {
        $("#toggle").toggle(function () {
            $(this).attr("value", "Read Contents");
            $(".comments").show();
            $("#contents").hide();
        },
    function () {
        $(this).attr("value", "Read Comments");
        $(".comments").hide();
        $("#contents").show();
    }
  );
    });
</script>